name: Run Config Scraper

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug directory (بررسی فایل‌های موجود)
      run: |
        echo "Current Directory:"
        pwd
        echo "--- Files in root ---"
        ls -la
        echo "--- Files inside 'Files' folder ---"
        ls -la Files/ || echo "Folder 'Files' does NOT exist here!"

    - name: Run Config Scraper
      run: python config_scraper.py

    - name: Commit and Push configs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update VPN configs" || echo "No changes to commit"
        git push
