name: Fetch and Update ECH Config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-ech-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch ECH Config using Dig
        run: |
          DOMAIN="crypto.cloudflare.com"
          echo "در حال دریافت اطلاعات DNS برای $DOMAIN با استفاده از ابزار dig..."
          
          # ابزار dig خودش دیتای خام را ترجمه کرده و رشته ech را به ما می‌دهد
          DIG_OUTPUT=$(dig HTTPS $DOMAIN +short)
          echo "خروجی خام dig:"
          echo "$DIG_OUTPUT"
          
          ECH_CONFIG=$(echo "$DIG_OUTPUT" | grep -oP 'ech="\K[^"]+' || true)
          
          if [ -z "$ECH_CONFIG" ]; then
            echo "خطا: کلید ECH استخراج نشد!"
            exit 1
          fi
          
          echo "$ECH_CONFIG" > ech_config.txt
          echo "کلید ECH با موفقیت به فرمت Base64 استخراج شد!"

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git add ech_config.txt
          
          if git diff-index --quiet HEAD; then
            echo "کلید ECH تغییری نکرده است. نیازی به کامیت نیست."
          else
            git commit -m "Auto-update ECH config [$(date -u +'%Y-%m-%d %H:%M:%S UTC')]"
            git push
            echo "فایل آپدیت و کامیت شد."
          fi
